# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastee_web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='paste_text',
        ),
    ]
